name: Deploy blog on release
run-name: ${{ gitea.actor }} deploy blog on ${{ gitea.event_name }}

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
      options: -v blog-data:/deploy/blog-data
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - run: |
          rm -rf /deploy/blog-data/*
          cp -r dist/* /deploy/blog-data/
