name: Deploy blog on release
run-name: ${{ gitea.actor }} deploy blog on ${{ gitea.event_name }}

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:24-trixie-slim
      options: -v blog-data:/deploy/blog-data
    steps:
      - name: Install system deps
        run: |
          apt-get update
          apt-get install -y rsync

      - name: Check out repository code
        uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build

      - name: Set release name
        run: echo "RELEASE=release-${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - run: |
          # rm -rf /deploy/blog-data/*
          mkdir -p /deploy/blog-data/$RELEASE
          rsync -az --delete dist/ /deploy/blog-data/$RELEASE
          cd /deploy/blog-data/ 
          ln -sfn $RELEASE current
          # ls -1t | tail -n +6 | xargs -r rm -rf
