name: Deploy blog on release
run-name: ${{ gitea.actor }} deploy blog on ${{ gitea.event_name }}

on: [push]

jobs:
 build:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        
        - name: Login to docker
          run: docker login gitea.b33th0v3n.com --username ${{secret.USERNAME}} --password ${{secret.REGISTRY_TOKEN}}
        
        - name: Set release name
          run: echo "RELEASE=release-${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

        - name: Build the Image
          run: docker build -t gitea.b33th0v3n.com/${{secret.USERNAME}}/blog:$RELEASE .

        - name: Push the Image
          run: docker push gitea.b33th0v3n.com/${{secret.USERNAME}}/blog:$RELEASE
